version: "3.3"

services:
  plex:
    image: ghcr.io/linuxserver/plex
    hostname: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    volumes:
      - ./library:/config
      - ./tv:/tv
      - ./movies:/movies
    restart: unless-stopped
